#!/usr/bin/env python3
"""
GitHub Integration for Niha's Learning Repository

This script helps:
1. Initialize GitHub repo for Niha's learning materials
2. Push daily lessons automatically
3. Agent can commit and push MD files

Usage:
    python github_integration.py init <github-username> <repo-name>
    python github_integration.py push "<commit-message>"
    python github_integration.py create-lesson <week> <day> "<title>" "<content>"
"""

import os
import sys
import json
import subprocess
from datetime import datetime
from pathlib import Path

REPO_DIR = Path(os.path.expanduser("~/.openclaw/workspace/neha-tutor"))
GITHUB_CONFIG = Path(os.path.expanduser("~/.openclaw/broadcaster/github_config.json"))

def run_cmd(cmd, cwd=None):
    """Run shell command and return output"""
    try:
        result = subprocess.run(
            cmd, shell=True, cwd=cwd or REPO_DIR,
            capture_output=True, text=True
        )
        return result.returncode == 0, result.stdout, result.stderr
    except Exception as e:
        return False, "", str(e)

def check_github_auth():
    """Check if GitHub CLI is authenticated"""
    success, stdout, _ = run_cmd("gh auth status")
    if success and "logged in" in stdout:
        return True
    return False

def login_github():
    """Guide user through GitHub login"""
    print("\n🔐 GitHub Login Required")
    print("Run: gh auth login")
    print("Choose: GitHub.com → HTTPS → Paste token")
    print("\nTo create a token: https://github.com/settings/tokens")
    print("Required scopes: repo, read:user\n")

def init_repo(github_username, repo_name):
    """Initialize GitHub repository for Niha's learning"""
    print(f"\n🚀 Initializing repository: {github_username}/{repo_name}")
    
    # Check auth
    if not check_github_auth():
        login_github()
        return False
    
    # Create repo on GitHub
    print("Creating GitHub repository...")
    success, _, stderr = run_cmd(f"gh repo create {repo_name} --public --description 'Niha\\'s AI Full Stack Developer Learning Journey - 8 Week Program'")
    
    if not success:
        # Repo might exist, try to clone
        print(f"Repository might exist. Cloning instead...")
        os.chdir(REPO_DIR.parent)
        success, _, _ = run_cmd(f"git clone https://github.com/{github_username}/{repo_name}.git neha-learning")
        if success:
            print(f"✅ Cloned existing repository")
            return True
        print(f"❌ Error: {stderr}")
        return False
    
    # Initialize git if not already
    if not (REPO_DIR / ".git").exists():
        os.chdir(REPO_DIR)
        run_cmd("git init")
        run_cmd("git add .")
        run_cmd(f'git commit -m "Initial commit: Niha\\'s Learning Repository"')
        run_cmd(f"git remote add origin https://github.com/{github_username}/{repo_name}.git")
        run_cmd("git push -u origin main")
    
    print(f"✅ Repository initialized: https://github.com/{github_username}/{repo_name}")
    return True

def create_lesson(week: int, day: int, title: str, content: str):
    """Create a lesson MD file"""
    lesson_dir = REPO_DIR / f"week-{week:02d}" / f"day-{day:02d}-{title.lower().replace(' ', '-')}"
    lesson_dir.mkdir(parents=True, exist_ok=True)
    
    # Create lesson.md
    lesson_file = lesson_dir / "lesson.md"
    lesson_content = f"""# Week {week}, Day {day}: {title}

**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Duration:** 2-3 hours

---

## 📖 Lesson Content

{content}

---

## 🎯 Today's Goals

- [ ] Complete the lesson
- [ ] Try the exercises
- [ ] Push your progress to GitHub

---

## 📚 Resources

- [Link 1]()
- [Link 2]()

---

## 💡 Tips

> "The best way to learn coding is by coding."

---

*Generated by Niha's AI Career Coach*
"""
    
    with open(lesson_file, 'w') as f:
        f.write(lesson_content)
    
    # Create exercises folder placeholder
    (lesson_dir / "exercises").mkdir(exist_ok=True)
    
    print(f"✅ Created lesson: {lesson_file}")
    return str(lesson_file)

def push_changes(message: str):
    """Commit and push changes to GitHub"""
    print(f"\n📤 Pushing to GitHub: {message}")
    
    os.chdir(REPO_DIR)
    
    # Add all changes
    run_cmd("git add .")
    
    # Commit
    success, _, stderr = run_cmd(f'git commit -m "{message}"')
    if not success:
        if "nothing to commit" in stderr:
            print("ℹ️  No changes to commit")
            return True
        print(f"❌ Commit error: {stderr}")
        return False
    
    # Push
    success, _, stderr = run_cmd("git push")
    if not success:
        print(f"❌ Push error: {stderr}")
        return False
    
    print("✅ Changes pushed to GitHub!")
    return True

def get_repo_url():
    """Get the GitHub repository URL"""
    os.chdir(REPO_DIR)
    success, stdout, _ = run_cmd("git remote get-url origin")
    if success:
        return stdout.strip()
    return None

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return
    
    command = sys.argv[1]
    
    if command == "init":
        if len(sys.argv) < 4:
            print("Usage: python github_integration.py init <username> <repo-name>")
            return
        init_repo(sys.argv[2], sys.argv[3])
    
    elif command == "push":
        message = " ".join(sys.argv[2:]) if len(sys.argv) > 2 else "Update learning materials"
        push_changes(message)
    
    elif command == "create-lesson":
        if len(sys.argv) < 7:
            print("Usage: python github_integration.py create-lesson <week> <day> <title> <content>")
            return
        create_lesson(
            int(sys.argv[2]),
            int(sys.argv[3]),
            sys.argv[4],
            sys.argv[5]
        )
    
    elif command == "status":
        url = get_repo_url()
        if url:
            print(f"📁 Repository: {url}")
        else:
            print("❌ Not initialized. Run: python github_integration.py init <username> <repo-name>")
    
    else:
        print(f"Unknown command: {command}")
        print(__doc__)

if __name__ == "__main__":
    main()
